### PR TITLE
fix: #383 render streaming text as markdown

### LINKED ISSUE #383: Accumulated TextChunk text content not rendered as markdown
When receiving the TextChunkEvent, the accumulation of text is not rendered through the usual markdown renderer, leading to a discrepancy between the accumulation and the final message rendering. The accumulation should go through the markdown renderer.

### PR DESCRIPTION
**Pull request by vincent-audibert-whoz**
## Problem
When receiving `TextChunkEvent`, the accumulated text was displayed as plain text without markdown rendering, creating a visual discrepancy between the streaming accumulation and the final message.

## Solution
Used `MarkdownService` injection in `ChatHistoryComponent`

Closes #383

### CODE REVIEW

File: apps/client/src/app/components/chat-history/chat-history.component.ts [hunk 1]
```diff
@@ -537,4 +549,24 @@ export class ChatHistoryComponent implements AfterViewChecked, OnInit, OnDestroy
...
+   */
+  private async renderStreamingText(): Promise<void> {
+    if (!this.streamingText) {
+      this.renderedStreamingText = ''
+      return
+    }
+
+    try {
+      const html = await this.markdownService.parse(this.streamingText)
+      this.renderedStreamingText = this.sanitizer.bypassSecurityTrustHtml(html)
```
Comment (vincent-audibert-whoz) [inline apps/client/src/app/components/chat-history/chat-history.component.ts]: Dig again on what can be done better here.

Comment (vincent-audibert-whoz) [reply apps/client/src/app/components/chat-history/chat-history.component.ts]: Added and used new lib: dompurify
